export const CREATOR = {
  name: "Isha Dhakal",
  handle: "_isha_dhakal_",
  email: "ishadhakal13@icloud.com",
  location: "Nepal",
  pronouns: "she/her",
  linktree: "https://linktr.ee/isha_dhakal",
  tiktok: "https://www.tiktok.com/@_isha_dhakal_",
  instagram: "https://www.instagram.com/_isha_dhakal_/",
  pinterest: "https://www.pinterest.com/ishaapins/",
  pinterestHandle: "ishaapins",
};

export const PUBLIC_PINS = [
  {
    id: "pin-twenty",
    title: "Twenty",
    caption: "A bright afternoon by the water, from Isha’s public Pinterest.",
    platform: "pinterest",
    kind: "photo",
    src: "/media/pin-board-a.jpg",
    externalUrl: CREATOR.pinterest,
    source: "pinterest",
  },
  {
    id: "pin-picnic",
    title: "Photo inspo",
    caption: "Cover from the Photo Inspo board.",
    platform: "pinterest",
    kind: "photo",
    src: "/media/pin-photo-inspo.jpg",
    externalUrl: `${CREATOR.pinterest}photo-inspo/`,
    source: "pinterest",
  },
  {
    id: "pin-sunset",
    title: "Golden hour",
    caption: "A public pin from ishaapins.",
    platform: "pinterest",
    kind: "photo",
    src: "/media/pin-grow.jpg",
    externalUrl: CREATOR.pinterest,
    source: "pinterest",
  },
  {
    id: "pin-beginnings",
    title: "Fresh beginnings",
    caption: "A quote pin from her public boards.",
    platform: "pinterest",
    kind: "photo",
    src: "/media/pin-quotes.jpg",
    externalUrl: CREATOR.pinterest,
    source: "pinterest",
  },
  {
    id: "pin-heart",
    title: "A quiet note",
    caption: "Another public pin from ishaapins.",
    platform: "pinterest",
    kind: "photo",
    src: "/media/pin-snap.jpg",
    externalUrl: CREATOR.pinterest,
    source: "pinterest",
  },
];

export const NAV = [
  { href: "/", label: "Dashboard", icon: "home" },
  { href: "/create", label: "Create Post", icon: "plus" },
  { href: "/content", label: "My Content", icon: "play" },
  { href: "/analytics", label: "Analytics", icon: "chart" },
  { href: "/collaboration", label: "Collaboration", icon: "heart" },
  { href: "/library", label: "Media Library", icon: "image" },
  { href: "/about", label: "About", icon: "user" },
  { href: "/admin", label: "Manage", icon: "gear" },
  { href: "/settings", label: "Settings", icon: "gear" },
];
