import type { Palette, PaletteId } from './types'

export const PALETTES: Palette[] = [
  {
    id: 'atelier',
    name: 'Atelier',
    note: 'Warm paper, terracotta',
    bg: '#F4F0E8',
    surface: '#FFFDF8',
    ink: '#1C1915',
    muted: '#6B6459',
    accent: '#C45C26',
    accent2: '#2F5D50',
    line: '#E4DCD0',
    onAccent: '#FFFDF8',
  },
  {
    id: 'editorial',
    name: 'Editorial',
    note: 'Ink and navy',
    bg: '#F7F4EF',
    surface: '#FFFFFF',
    ink: '#111111',
    muted: '#5C5852',
    accent: '#1F4E79',
    accent2: '#B42318',
    line: '#E6E1D8',
    onAccent: '#FFFFFF',
  },
  {
    id: 'sage',
    name: 'Sage',
    note: 'Garden and gold',
    bg: '#EEF3EE',
    surface: '#FBFFFB',
    ink: '#1C2B21',
    muted: '#5A6B60',
    accent: '#3D6B54',
    accent2: '#B8860B',
    line: '#D7E2D8',
    onAccent: '#FBFFFB',
  },
  {
    id: 'midnight',
    name: 'Midnight',
    note: 'Dark board, brass',
    bg: '#12141A',
    surface: '#1B1E27',
    ink: '#F3EFE6',
    muted: '#A39B8F',
    accent: '#E8B86D',
    accent2: '#7EB8A8',
    line: '#2A2E3A',
    onAccent: '#12141A',
  },
  {
    id: 'paper',
    name: 'Paper',
    note: 'Quiet cream',
    bg: '#FBF7F0',
    surface: '#FFFFFF',
    ink: '#2A241C',
    muted: '#7A7268',
    accent: '#8C4A2F',
    accent2: '#3F5B6B',
    line: '#EDE6DA',
    onAccent: '#FFFDF8',
  },
  {
    id: 'noir',
    name: 'Noir',
    note: 'High contrast',
    bg: '#0E0E0E',
    surface: '#171717',
    ink: '#F7F4EE',
    muted: '#9A958C',
    accent: '#F2F0EA',
    accent2: '#D4734A',
    line: '#2C2C2C',
    onAccent: '#0E0E0E',
  },
]

export function getPalette(id: PaletteId): Palette {
  return PALETTES.find((p) => p.id === id) ?? PALETTES[0]
}
